Project Set up
simekanidvt/Workout-Manager pull request #1
Opened 2022-02-23 18:06 UTC by simekanidvt

This reverts commit 7e606efcdd463ae87a3cfed74a1c0e4d506c05b4.

2022-02-23 18:13 UTC, bgouws requested changes
Just double check that SwiftLint is working correctly 👍

2022-02-23 18:13 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewController.swift
> +
Think you should have warning here for all these line breaks? if not make sure your SwiftLint is working properly 😄

2022-02-23 18:16 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/ViewController.swift
> +
I actually forgot to add swift lint. Let me do that quickly. Thanks Brandon🙏

2022-02-23 18:54 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/ViewController.swift
> +
I have made added swift lint now in the following commit ad5c16432695293f1d35647eb9605a1c3f41ce37

2022-02-24 17:24 UTC, bgouws requested changes
Looks good man, just please add .DS_Store files to your .gitignore 😄

2022-02-24 17:24 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            return 1
Rather return a 0 here 😄

2022-02-24 17:24 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/UserViewController.swift
> +    // Creates an array of users that we can reference the data
Ideally we don't want to commit comments 😄

2022-02-24 17:51 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            return 1
So I returned one because I want to display a message saying "No Workout plans found" in the table view. Or should I use another method to achieve this?

2022-02-24 17:54 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            return 1
Hmm I see, yeah sure you can leave it like this for now 😄 we'll show you guys some better ways in the near future.

2022-02-24 17:54 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/UserViewController.swift
> +    // Creates an array of users that we can reference the data
Should I just remove comments there or everywhere else in the project?

2022-02-24 17:55 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            return 1
Perfect Thanks😄

2022-02-24 18:02 UTC, simekanidvt reviewed
I have made all changes that were requested

2022-02-25 04:58 UTC, bgouws requested changes

2022-02-25 04:58 UTC, bgouws commented on .gitignore
> +.DS_Store
Think that *.DS_Store might be more appropriate 😄 this should ignore all .DS_Store files. 

You will also need to go and manually remove the ones that you have already committed.

2022-02-25 04:58 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        // Get All Workout plans for us
So you can remove all the comments from the codebase. If you want you can leave the ones in the `SceneDelegate`  and `AppDelegate` but other than that they can be removed 😄

2022-02-25 05:59 UTC, simekanidvt commented on .gitignore
> +.DS_Store
Perfect Will do

2022-02-25 05:59 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        // Get All Workout plans for us
Got it👌

2022-02-25 06:11 UTC, bgouws requested changes
Remember to remove those comments.

2022-02-25 06:39 UTC, bgouws approved these changes
Looks good man 😄

2022-02-25 13:52 UTC, bgouws requested changes
Just a small update

2022-02-25 13:52 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/UserViewController.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:User.self, completion: {result in
Just remember to add `[weak self]` here 👍

2022-02-28 06:08 UTC, kirsty14 reviewed
Very well done. I would suggest that youI remove all comments from every file as we do not want comments in main or develop

2022-02-28 06:08 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Config/AppDelegate.swift
> +        // Override point for customization after application launch.
Ideally we don't want to commit comments to main and develop even if they are autogenerated.

2022-02-28 06:08 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Config/SceneDelegate.swift
> +        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
I would remove the comments here as well

2022-02-28 06:08 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +
I would remove the spacing here in this function so that each line is underneath each other to make the code more readable.

2022-02-28 06:08 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Utilities/URLSession+Extension.swift
> +        // Creates a request that we can work with and parse information
I would remove the comments here as well

2022-02-28 06:08 UTC, kirsty14 commented on WorkoutManager/WorkoutManagerTests/WorkoutManagerTests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
I would remove the comments here

2022-02-28 06:19 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/UserViewController.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:User.self, completion: {result in
Will do👍

2022-02-28 06:20 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Config/AppDelegate.swift
> +        // Override point for customization after application launch.
Will Do.

2022-02-28 06:23 UTC, bgouws approved these changes
Looks good man 😄

2022-02-28 08:34 UTC, kirsty14 approved these changes
I am happy with this

2022-02-28 08:56 UTC, smabhena approved these changes
Looks good 👍

2022-02-28 09:26 UTC, tmafaralala approved these changes
all good👍

2022-02-28 09:43 UTC, merged