Workout Plan Page
simekanidvt/Workout-Manager pull request #10
Opened 2022-03-31 09:40 UTC by simekanidvt

*  Workout Plan Page which will lead from the landing page done with mock data
* Collection view redone on the landing page and reverted to a conventional collection view
* Changed my folder structure to separate it by features

<img width="412" alt="Screenshot 2022-03-31 at 11 39 03" src="https://user-images.githubusercontent.com/100220689/161025946-a8abcfe0-85cb-4c98-a376-21a102ed620c.png">

2022-03-31 19:38 UTC, bgouws requested changes
Just some cleaning looks pretty solid though 👏

2022-03-31 19:38 UTC, bgouws commented on WorkoutManager/WorkoutManager/LandingPage/WorkoutManagerViewController.swift
> +extension WorkoutManagerViewController {
Would be a little bit neater to declare this like this:

`extension WorkoutManagerViewController: WorkoutManagerDelegate {`

2022-03-31 19:38 UTC, bgouws commented on WorkoutManager/WorkoutManager/LandingPage/WorkoutManagerViewController.swift
> +    private lazy var viewModel = WorkoutManagerViewModel(delegate: self,repository: WorkoutManagerRepository())
Small code style think but put these parameters on their own line 😄

2022-03-31 19:38 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutPlanItem.swift
> +        return 8
So normally hardcoded values are a warning sign, also is this a UITableView within a cell?

2022-03-31 19:38 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewController.swift
> +        return 5
This should also be a warning sign, unless you are still making use of some mock data?

2022-03-31 19:38 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutPlanItem.swift
> +        return 8
So I had a look at your screenshots 😄 thanks for including them 👍 if you are using mock data for now that is fine, but obviously once we have actual data we can expect this to be much more dynamic.

2022-04-01 07:44 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutPlanItem.swift
> +        return 8
Perfect, When i include my API this will change

2022-04-01 10:13 UTC, bgouws approved these changes

2022-04-02 05:34 UTC, kirsty14 approved these changes
Looking good 👍🏻

2022-04-04 06:25 UTC, merged