Workout plan Page
simekanidvt/Workout-Manager pull request #18
Opened 2022-04-12 12:47 UTC by simekanidvt

This PR in have included some logic to my workout item page.
I pull info from my API and populate my views with the data.
I have also included Unit tests for the associated.

2022-04-13 21:25 UTC, bgouws requested changes
Just some general clean up.

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutInfoTableViewCell.swift
> +    @IBOutlet private weak var numberOfSets: UILabel!
A line to separate your outlets and your vars would improve readability 😄

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutPlanItem.swift
> +        guard let exercise = workoutDay?.exercises?[indexPath.item] else {
Small coding style enhancement: 

`guard let exercise = workoutDay?.exercises?[indexPath.item] else { return }`

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutPlanItem.swift
> +        cell.setData(exercise:exercise)
Space here 😄 
`cell.setData(exercise: exercise)`

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/Models/WorkoutPlansInfo.swift
> +struct WorkoutPlanDetails: Codable {
So just a naming tip here 😄 if it's a model, let's include model in the name so other developers can quickly know what they are working with: 

`WorkoutPlanDetailsModel`

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/Repository/WorkoutPlansRepository.swift
> +protocol WorkoutPlansRepositoryType:AnyObject {
Spacing: 
`protocol WorkoutPlansRepositoryType: AnyObject {`

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewController.swift
> +    func showError(error: String) {
Should these be empty? if yes consider creating another delegate for this functionality that excludes these functions.

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewModel.swift
> +    func getWorkoutPlan() -> WorkoutPlan? {
This can be a `var`

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewModel.swift
> +
Extra line here 😄

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewModel.swift
> +    public func getWorkoutInfo(itemIndex:Int) -> Day? {
Three things here:

1. No real need to mark this public -technically it is already public, not wrong but just not necessary 😄 
2. Try to avoid the prefix "get" we ideally want our code to read like a sentence i.e. `workoutInfo(at index: Int)`
3. Spacing for the parameter 😄

2022-04-13 21:25 UTC, bgouws commented on WorkoutManager/WorkoutManagerTests/WorkoutPlanPageTests/WorkoutPlanPageTests.swift
> +        // viewModel.setWorkoutPlan(nil)
Commented code here.

2022-04-14 07:06 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/CustomCells/WorkoutInfoTableViewCell.swift
> +    @IBOutlet private weak var numberOfSets: UILabel!
I agree 👍🏻

2022-04-14 07:06 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/Models/WorkoutPlansInfo.swift
> +struct WorkoutPlanDetails: Codable {
I agree 👍🏻

2022-04-17 15:59 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/WorkoutPlanPage/WorkoutPlansViewController.swift
> +    func showError(error: String) {
I will still add code here

2022-04-19 05:12 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/LandingPage/WorkoutManagerViewController.swift
> +            viewController.setWorkoutPlan(workoutPlan: (self.viewModel.workoutPlan(atIndex: workoutPlanIndex)!))
Done

2022-04-19 05:44 UTC, kirsty14 approved these changes
Looking good 👍🏻

2022-04-20 05:02 UTC, bgouws approved these changes
Looks good 😄

2022-04-20 07:22 UTC, merged