Launch -> Login -> Landing Page
simekanidvt/Workout-Manager pull request #2
Opened 2022-02-28 09:42 UTC by simekanidvt

2022-02-28 11:46 UTC, tmafaralala commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +        }
Since the two guard lets do the same thing, i'd consider chaining them with a comma just to have less code, something like this: https://agrawalsuneet.github.io/blogs/if-vs-if-let-vs-guard-let-in-swift/#:~:text=In%20if%20let%20%2C%20the%20defined,the%20function%20ends%20or%20anything.

2022-02-28 11:51 UTC, tmafaralala submitted a review, later dismissed
Good job!

2022-02-28 12:44 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +        }
Great Suggestion, thanks 🤛

2022-02-28 15:45 UTC, kieranwoodrow submitted a review, later dismissed
Looking good bro. Keep it up😁

2022-02-28 20:14 UTC, bgouws requested changes
Just a little bit of clean up 😄

2022-02-28 20:14 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/UserViewController.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:User.self, completion: {result in
Remember to add `[weak self]`

2022-02-28 20:14 UTC, bgouws commented on WorkoutManager/WorkoutManager/Utilities/URLSession+Extension.swift
> +    // Known errors we want to listen for
All these comments can also be removed

2022-03-03 07:13 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +        guard let password = passwordField.text , let username = userNameField.text  else {
Fixed in latest commit.👍

2022-03-03 08:58 UTC, kieranwoodrow approved these changes
Keep it up bro

2022-03-03 20:12 UTC, bgouws submitted a review, later dismissed
Happy from my side 😄

2022-03-06 14:52 UTC, smabhena approved these changes
LGTM 👍

2022-03-06 18:00 UTC, bgouws submitted a review, later dismissed
Looks good!

2022-03-07 20:13 UTC, bgouws commented
Reach out to your peers so that we can get this merged.

2022-03-08 05:47 UTC, kirsty14 reviewed
If you make all your IBoutlets private I will approve this pull request

2022-03-08 05:47 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +    @IBOutlet weak var userNameField: UITextField!
Still waiting for this change

2022-03-08 06:13 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +    @IBOutlet weak var passwordField: UITextField!
You can also make this IBoutlet private

2022-03-08 06:16 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +    @IBOutlet weak var userNameField: UITextField!
Could you possibly also add a description and screenshots of your Pull request so that it gives us reviewers more insight visually into what the changes are.

2022-03-08 06:21 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +    @IBOutlet weak var passwordField: UITextField!
Done👍

2022-03-08 06:22 UTC, kirsty14 approved these changes
Looking good!

2022-03-08 06:28 UTC, smabhena commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +
May want to remove the white space after the function name just to make your code a bit cleaner

2022-03-08 06:29 UTC, smabhena submitted a review, later dismissed
Just some clean up but it looks good 👍

2022-03-08 06:32 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/LoginViewController.swift
> +
Done👍

2022-03-08 06:37 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/UserInterfaces/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LogoOnly" tran
I know this is not the right place to put my comment. I need to put it into the main.storyboard but I cannot add it there. Looking at your screenshot specifically your label that says log into your profile. Your label is actually being cut off. What I would do is in your Main.storyboard I would select this label and give it a top constraint of 40 so that it odes not get cut off

2022-03-08 06:40 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/UserInterfaces/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LogoOnly" tran
No problem, I did notice that and fixed it in my other feature so that update will reflect in my next PR.

2022-03-08 06:46 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/UserInterfaces/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LogoOnly" tran
Perfect. As that type of thing drives me mad😆

2022-03-08 07:34 UTC, kieranwoodrow approved these changes
Looking good bro

2022-03-08 07:34 UTC, kirsty14 approved these changes

2022-03-08 12:15 UTC, bgouws approved these changes
Looks good 😄

2022-03-08 12:39 UTC, merged