Landing Page -> Section 1
simekanidvt/Workout-Manager pull request #4
Opened 2022-03-15 13:16 UTC by simekanidvt

I have implemented a collection view on landing page and i have done this using Compositional Layouts. In this PR i have only done the first section and will be adding more sections this week.

<img src="https://user-images.githubusercontent.com/100220689/158386252-536798bb-048e-4cfd-a0d2-b60b59990b5b.png" height="400"  width="200"/>

![Screenshot 2022-03-15 at 15 15 44](https://user-images.githubusercontent.com/100220689/158385853-481e587a-7ef3-4eb6-8e3f-e08251c6d3bb.png)

2022-03-15 14:42 UTC, kirsty14 reviewed
It is looking really cool Simekani

2022-03-15 14:42 UTC, kirsty14 commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    func setCellProperties(image: UIImage, label: String) {
Could this not be added to an extension?

2022-03-15 15:35 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    func setCellProperties(image: UIImage, label: String) {
It could but I don't think it would make much of a difference since this class doesn't have much in it. Its only specific to this cell's styling

2022-03-15 20:43 UTC, bgouws requested changes
Just some clean up 😄

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            cell.setCellProperties(image: UIImage(named: "workout1")!, label: (finalWorkouts[indexPath.row].name))
Some force unwrapping here 😄

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:WorkoutManager.self, completion: {[weak self]result in
spacing here at the end of the line:

`URLSession.shared.makeRequest(url: url,method: .get, returnModel:WorkoutManager.self, completion: { [weak self] result in`

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/MusleWorkoutsCollectionViewCell.swift
> +    override func awakeFromNib() {
You can remove this function 😄 it is just calling `super` so no need to `override` it.

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    override func awakeFromNib() {
You can remove this function.

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +        self.imageView.layer.borderColor = UIColor(named: "Primary Colour")?.cgColor
Access this colour from your style kit 😄

2022-03-15 20:43 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    func setCellProperties(image: UIImage, label: String) {
I think @kirsty14 made a good suggestion here 😄 for the time being an `extension` may be the best option (There are better ways to handle custom views, cells etc.) but for right now you could have a function in an extension to style your cell. So that if you ever needed to reuse it or update it, it would be in one place.

2022-03-16 07:00 UTC, tmafaralala submitted a review, later dismissed

2022-03-16 07:00 UTC, smabhena submitted a review, later dismissed

2022-03-16 07:29 UTC, kirsty14 approved these changes
Looking good

2022-03-16 13:35 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +            cell.setCellProperties(image: UIImage(named: "workout1")!, label: (finalWorkouts[indexPath.row].name))
This still needs to be addressed, please make sure that you have pushed all your code.

2022-03-16 13:35 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:WorkoutManager.self, completion: {[weak self]result in
This also still needs to be addressed.

2022-03-16 13:36 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/MusleWorkoutsCollectionViewCell.swift
> +    override func awakeFromNib() {
This also still needs to be addressed.

2022-03-16 13:36 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    override func awakeFromNib() {
This still needs to be addressed 😄

2022-03-16 13:36 UTC, bgouws commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +        self.imageView.layer.borderColor = UIColor(named: "Primary Colour")?.cgColor
Still needs to be addressed.

2022-03-16 13:37 UTC, bgouws requested changes

2022-03-16 13:37 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +                    guard let workouts = self?.workouts?.workoutPlans else { return}
Spacing here: 

`guard let workouts = self?.workouts?.workoutPlans else { return }`

2022-03-16 14:26 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/UserInterfaces/CollectionViewCells/WorkoutPlanCollectionViewCell.swift
> +    func setCellProperties(image: UIImage, label: String) {
Alright perfect

2022-03-16 18:22 UTC, tmafaralala approved these changes
Great stuff👍. Looks Impressive

2022-03-16 20:56 UTC, bgouws approved these changes

2022-03-17 05:57 UTC, merged