Feature refactor landing page
simekanidvt/Workout-Manager pull request #9
Opened 2022-03-24 12:00 UTC by simekanidvt

2022-03-24 12:12 UTC, kirsty14 submitted a review, later dismissed
Looks good to me 👍🏻

2022-03-25 05:24 UTC, bgouws commented
This should be going to develop.

2022-03-25 07:18 UTC, kirsty14 submitted a review, later dismissed
Looking good 👍🏻

2022-03-25 11:48 UTC, kirsty14 submitted a review, later dismissed

2022-03-25 12:50 UTC, bgouws requested changes
Some clean up

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        DispatchQueue.main.async {
Please put this in service layer 😄

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
> +        DispatchQueue.main.async {
Please put this in service layer 😄

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/Repository/WorkoutManagerRepository.swift
> +        URLSession.shared.makeRequest(url: url,method: .get, returnModel:WorkoutManager.self, completion: completion)
Very nice 😄👍

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
>      private var workoutSnapshot: WorkoutManagerSnapShot!
Think that it might be best to revert to a normal `UICollectionView` setup.

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +    var workoutManager: WorkoutManager?
This name is a little bit unclear, it doesn't really sound like data -it sounds like some sort of helper class.

Consider renaming it.

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +                print(error)
You can handle this error.

2022-03-25 12:50 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +        repository?.fetchWorkoutPlans(completion: {[weak self] result in
`repository?.fetchWorkoutPlans(completion: { [weak self] result in`

2022-03-27 18:37 UTC, simekanidvt commented on WorkoutManager/WorkoutManager/Controllers/WorkoutManagerViewController.swift
>      private var workoutSnapshot: WorkoutManagerSnapShot!
Will do

2022-03-28 05:24 UTC, bgouws requested changes
Some clean up.

2022-03-28 05:24 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +    var workoutPlansInfo: WorkoutManager?
This can be private 😄

2022-03-28 05:24 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +    weak var delegate: WorkoutManagerDelegate?
This can be `private` 😄

2022-03-28 05:24 UTC, bgouws commented on WorkoutManager/WorkoutManager/ViewModels/WorkoutManagerViewModel.swift
> +    var repository: WorkoutManagerRepositoryType?
This too.

2022-03-28 05:47 UTC, kirsty14 reviewed
Looking good. Just make sure you handle the error inside your workoutManagerViewModel.swift file

2022-03-28 10:45 UTC, bgouws approved these changes
Looks good 😄

2022-03-28 11:24 UTC, merged